title: Abhik Ghosh | Work
description: This slice if internet contains my collection of work and projects.
show_downloads: false
show_downloads_button: false
google_analytics:
theme: jekyll-theme-slate